# Generated by Django 2.2.7 on 2019-11-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yacad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='first_name',
            new_name='gearbox',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year_of_birth',
        ),
    ]
