# Generated by Django 2.2.7 on 2019-11-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yacad', '0003_auto_20191109_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Continent',
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name_plural': 'Continents'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='country',
            new_name='continent',
        ),
    ]
